export const data = [
  {
    id: 1,
    name: "Đỉnh Fansipan",
    location: "Lào Cai, Việt Nam",
    dateHike: "2023-07-20",
    selectedIndex: 0,
    lenghtHight: 3143,
    level: "Khó",
    desc: "Đỉnh Fansipan là đỉnh núi cao nhất Việt Nam và Đông Dương, nằm ở dãy Hoàng Liên Sơn, tỉnh Lào Cai. Đỉnh Fansipan được mệnh danh là `Nóc nhà Đông Dương` và là điểm đến du lịch nổi tiếng của Việt Nam.",
  },
  {
    id: 2,
    name: "Núi Tà Xùa",
    location: "Hòa Bình, Việt Nam",
    dateHike: "2023-07-21",
    selectedIndex: 1,
    lenghtHight: 2865,
    level: "Trung bình",
    desc: "Núi Tà Xùa là một dãy núi thuộc tỉnh Hòa Bình, Việt Nam. Dãy núi này nằm cách thị trấn Mộc Châu khoảng 30 km về phía Tây. Tà Xùa được mệnh danh là `Sa Pa thứ hai` của Việt Nam.",
  },
  {
    id: 3,
    name: "Núi Ba Vì",
    location: "Hà Nội, Việt Nam",
    dateHike: "2023-07-22",
    selectedIndex: 2,
    lenghtHight: 1281,
    level: "Dễ",
    desc: "Núi Ba Vì là một dãy núi nằm ở phía Tây thủ đô Hà Nội, Việt Nam. Dãy núi này nằm cách trung tâm thành phố Hà Nội khoảng 60 km. Ba Vì được mệnh danh là `lá phổi xanh của Hà Nội`.",
  },
  {
    id: 4,
    name: "Núi Tam Đảo",
    location: "Vĩnh Phúc, Việt Nam",
    dateHike: "2023-07-23",
    selectedIndex: 3,
    lenghtHight: 1592,
    level: "Trung bình",
    desc: "Núi Tam Đảo là một dãy núi nằm ở tỉnh Vĩnh Phúc, Việt Nam. Dãy núi này nằm cách trung tâm thành phố Hà Nội khoảng 80 km. Tam Đảo được mệnh danh là Đà Lạt của miền Bắc.",
  },
];
